config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :managements do
    get 'index', as: :'', path: ''
    resources :kind_of_scholarships
    resources :profiles, path: 'students', only: [:index, :show]
  end

  resources :profiles, path: 'student', except: [:index, :destroy]

  root 'home#index'

  get 'about' => 'home#about', as: :about

end

app/views/shared/_common_menu.html.erb
<li>
	<%= link_to 'Iniciar Sesion', new_user_session_path %>
</li>
<li>
	<%= link_to 'Registrarme', new_user_registration_path %>	
</li>

app/views/shared/_filter_selector.html.erb
<%= collection_select(:filter, "Becas", Scholarship.find(:all, :id, :tipoBeca, :include_blank => true, :selected => params[:filter])

app/views/shared/_manager_menu.html.erb
<li>
	<%= link_to fa_icon("user", text: "Admin area"), managements_path %>
</li>
<li>
	<%= link_to fa_icon("sign-out", text: "Cerrar sesión"), destroy_user_session_path, method: :delete %>
</li>

app/views/shared/_messages.html.erb
<% if notice %>
        <div class="alert alert-success alert-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
          <strong><%= notice %></strong>
        </div> 
  <% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <strong><%= alert %></strong>
  </div>
<% end %>

app/views/shared/_non_student_menu.html.erb
<li class='col-md'> <%= link_to "Cargar perfil", new_profile_path %> </li>
<li class='col-md'> <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %> </li>

app/views/shared/_student_menu.html.erb
<li>
	<%= link_to current_user.profile, :class => 'button white' do %>
		<span id="span" class="fa-stack fa-lg pull-left"><i class="fa fa-user fa-stack-1x "></i></span> <%= current_user.profile.personal_datum.name %>
	<% end %>
</li>
<li>
	<%= link_to destroy_user_session_path, method: :delete, :class => 'button white' do %>
		<span id="span" class="fa-stack fa-lg pull-left"><i class="fa fa-sign-out fa-stack-1x "></i></span> Cerrar Sesión
	<% end %>
</li>