config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :managements do
    get 'index', as: :'', path: ''
    resources :kind_of_scholarships
    resources :profiles, path: 'students', only: [:index, :show]
  end

  resources :profiles, path: 'student', except: [:index, :destroy]

  root 'home#index'

  get 'about' => 'home#about', as: :about

end

app/models/kind_of_scholarship.rb
class KindOfScholarship < ActiveRecord::Base
  has_many :scholarship_requests
  has_attached_file :cover, :styles => { :cover => "500x300" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  #validates :name, :description, :short_description, :state, :starting_date, :ending_date, presence: true
  #validates :name, uniqueness: true
  ################# OBJECTS METHODS


end

app/controllers/managements/kind_of_scholarships_controller.rb
class Managements::KindOfScholarshipsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_kind_of_scholarship, only: [:show, :edit, :update, :destroy]
  before_action :set_kind_of_scholarships
  layout "management"
  # GET /kind_of_scholarships
  # GET /kind_of_scholarships.json
  def index
    @kind_of_scholarships = KindOfScholarship.all
  end

  # GET /kind_of_scholarships/1
  # GET /kind_of_scholarships/1.json
  def show
  end

  # GET /kind_of_scholarships/new
  def new
    @kind_of_scholarship = KindOfScholarship.new
    @s_btn = 'Crear'
  end

  # GET /kind_of_scholarships/1/edit
  def edit
  end

  # POST /kind_of_scholarships
  # POST /kind_of_scholarships.json
  def create
    @kind_of_scholarship = KindOfScholarship.new(kind_of_scholarship_params)
    @s_btn = 'Crear'

    respond_to do |format|
      if @kind_of_scholarship.save
        format.html { redirect_to managements_path, notice: 'Kind of scholarship was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /kind_of_scholarships/1
  # PATCH/PUT /kind_of_scholarships/1.json
  def update
    respond_to do |format|
      if @kind_of_scholarship.update(kind_of_scholarship_params)
        format.html { redirect_to managements_path, notice: 'Kind of scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind_of_scholarship }
      else
        format.html { render :edit }
        format.json { render json: @kind_of_scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kind_of_scholarships/1
  # DELETE /kind_of_scholarships/1.json
  def destroy
    @kind_of_scholarship.destroy
    respond_to do |format|
      format.html { redirect_to managements_path, notice: 'Kind of scholarship was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind_of_scholarship
      @kind_of_scholarship = KindOfScholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_of_scholarship_params
      params.require(:kind_of_scholarship).permit(:name, :description, :short_description, :state, :starting_date, :ending_date, :cover)
    end
end

app/controllers/managements/profiles_controller.rb
class Managements::ProfilesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_kind_of_scholarships
  layout "management"
  def index
    @students = Profile.all
  end
  def show
    @student = Profile.find(params[:id])
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
	before_action :authenticate_admin!
	before_action :set_kind_of_scholarships
  layout "management"
  def index
		@scholarships = KindOfScholarship.all.count
		@profiles = Profile.all.count
		@requests = ScholarshipRequest.all.count
  end


end

app/helpers/kind_of_scholarships_helper.rb
module KindOfScholarshipsHelper
  def get_date(date)
    return "fecha"
  end
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/kind_of_scholarships/_form.html.erb
<%= simple_form_for [:managements, @kind_of_scholarship] do |f| %>
  <div class="row">
    <div class="row col-md-6">
      <div class="form-group col-md-12">
        <%= f.input :name, label:'Título' %>
      </div>

      <div class="col-md-6">
        <%= f.input :starting_date, label:'Inicio', as: :date_time_picker, input_html:
        { data:
          {
            date_format: "DD-MM-YYYY",
            date_view_mode: 'months',
          }
          } %>
      </div>

      <div class="col-md-6">
        <%= f.input :ending_date, label:'Fin', as: :date_time_picker, input_html:
        { data:
          {
            date_format: "DD-MM-YYYY",
            date_view_mode: 'months',
          }
          } %>
      </div>

    </div>
    <div class="row col-md-6">
      <%= f.input :short_description, label:'Breve descripción', input_html: { rows: 5, placeholder: 'Breve descripción de la beca' } %>
    </div>
  </div>

  <div class="row">
    <%= f.input :description, label:'Descripción',input_html: {:rows => 15, class: 'tinymce' } %>
    <%= tinymce  %>
  </div>
  <div class="row">
    <%= f.input :state,
    collection: ['Habilitada','Deshabilitada'],
    label:'Estado',wrapper_html: { class: 'col-md-4' } %>
    <%= f.input :cover, label:'Imagen',wrapper_html: { class: '' } %>
  </div>
  <%= f.button :submit, 'Guardar' %>
<% end %>

app/views/managements/kind_of_scholarships/_form_old.html.erb
<%= form_for([:managements, @kind_of_scholarship],html: {id: "sch_types_form"}) do |f| %>
  <% if @kind_of_scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind_of_scholarship.errors.count, "error") %> prohibited this kind_of_scholarship from being saved:</h2>

      <ul>
      <% @kind_of_scholarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="row col-md-6">
      <div class="form-group col-md-12">
        <%= f.label :name, 'Título' %><br>
        <%= f.text_field :name, class: 'form-control', placeholder: "Título sin el 'Beca de...' " %>
      </div>
      <div class="form-group date_time_picker optional col-md-6">
        <label class="date_time_picker optional control-label" for="event_when">Inicio de inscripcion</label>
        <div class="input-group date datetime_picker">
          <input class="string date_time_picker optional form-control" type="text" data-date-format="DD-MM-YYYY" data-date-extra-formats="[&quot;YYYY-MM-DD HH:mm:ss ZZ&quot;]" name="kind_of_scholarship[starting_date]" id="kind_of_scholarship_starting_date">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-calendar"></i></button>
          </span>
        </div>
      </div>
      <div class="form-group date_time_picker optional col-md-6">
        <label class="date_time_picker optional control-label" for="event_when">Fin de inscripcion</label>
        <div class="input-group date datetime_picker">
          <input class="string date_time_picker optional form-control" type="text" data-date-format="DD-MM-YYYY" data-date-extra-formats="[&quot;YYYY-MM-DD HH:mm:ss ZZ&quot;]" name="kind_of_scholarship[ending_date]" id="kind_of_scholarship_ending_date">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-calendar"></i></button>
          </span>
        </div>
      </div>
    </div>
    <div class="row col-md-6">
      <div class="form-group">
        <%= f.label :short_description, 'Descripción breve' %><br>
        <%= f.text_area :short_description, class: 'form-control', :rows => 5 %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Descripción' %><br>
    <%= f.text_area :description, :class => "tinymce form-control", :rows => 15 %>
    <%= tinymce  %>
  </div>
  <div class="form-group">
    <%= f.label :state, 'Estado' %><br>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cover %>
    <%= f.file_field :cover, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit @s_btn, class:'btn btn-info' %>
  </div>

<% end %>

app/views/managements/kind_of_scholarships/destroy.js.erb
$("#sch_<%= @kind_of_scholarship.id %>").fadeOut();

app/views/managements/kind_of_scholarships/edit.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h1><%= "Editar beca #{@kind_of_scholarship.name}" %></h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Volver', managements_path, class:'btn btn-lg btn-warning' %>
  </div>
</div>

app/views/managements/kind_of_scholarships/index.html.erb
<h1>Listado de Becas</h1>
<div class="dataTable_wrapper">
  <table class="table table-striped table-hover" id="dataTables-scholarships">
   <thead>
     <tr>
       <th>Nombre</th>
       <th>Estado</th>
       <th>Solicitudes</th>
       <th>Fecha inicio</th>
       <th>Fecha fin</th>
       <th>Opciones</th>
     </tr>
   </thead>
   <tbody>
     <% @kind_of_scholarships.each do |sch| %>
       <tr class="odd gradeX" id="sch_<%= "#{sch.id}" %>">
         <td><%= sch.name %></td>
         <td><%= sch.state %></td>
         <td><%= '#' %></td>
         <td><%= custom_datetime sch.starting_date %></td>
         <td><%= custom_datetime sch.ending_date %></td>
         <td>
           <%= link_to 'Show', managements_kind_of_scholarship_path(sch) %> |
           <%= link_to 'Edit', edit_managements_kind_of_scholarship_path(sch) %> | 
           <%= link_to 'Destroy', managements_kind_of_scholarship_path(sch), method: :delete, data: { confirm: 'Are you sure?' }, remote:true %>
         </td>
       </tr>
     <% end %>
   </tbody>
  </table>
  <%= link_to fa_icon("plus-circle", text: "Nueva beca"), new_managements_kind_of_scholarship_path, class:'btn btn-info' %>
  </div>
  <!-- /.table-responsive -->


<script>
  $(document).ready(function() {
    $('#dataTables-scholarships').DataTable({
      responsive: true
    });
  });
</script>

app/views/managements/kind_of_scholarships/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h1>Nueva Beca</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Volver', managements_path, class:'btn btn-lg btn-warning' %>
  </div>
</div>

app/views/managements/kind_of_scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kind_of_scholarship.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kind_of_scholarship.description %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @kind_of_scholarship.short_description %>
</p>

<p>
  <strong>State:</strong>
  <%= @kind_of_scholarship.state %>
</p>

<p>
  <strong>Starting date:</strong>
  <%= @kind_of_scholarship.starting_date %>
</p>

<p>
  <strong>Ending date:</strong>
  <%= @kind_of_scholarship.ending_date %>
</p>

<%= link_to 'Edit', edit_managements_kind_of_scholarship_path(@kind_of_scholarship) %> |
<%= link_to 'Back', managements_path %>